# events 블록 추가
events {
    worker_connections 1024;  # 연결 수를 설정 (필수는 아님, 기본값으로 적당)
}

http {
    # 여러 서버 설정을 여기에 추가할 수 있습니다
    server {
        listen 3000;  # Nginx가 3000번 포트에서 요청을 처리하도록 설정
        server_name localhost;

        root /usr/share/nginx/html;  # 프론트엔드 파일의 경로

        # 프론트엔드 경로
        location / {
            try_files $uri $uri/ =404;
        }

        
        location /callback {
            rewrite ^/callback$ /callback.html break;
        }

        location /vuln {
            rewrite ^/vuln$ /vuln.html break;
        }

        location /login {
            rewrite ^/login$ /login.html break;
        }

        location /index {
            rewrite ^/index$ /index.html break;
        }
        
        include mime.types;

        # 백엔드 API 요청을 Spring Boot 애플리케이션으로 프록시
        location /api/ {
            proxy_pass http://localhost:3030;  # Spring Boot 컨테이너 이름과 포트를 사용
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
